namespace HexGuard.ProblemDetails;

/// <summary>
/// RFC 9457 Problem Details — a standard machine-readable format for HTTP
/// error responses. Use <see cref="ProblemDetailsBuilder"/> to construct instances.
/// </summary>
/// <param name="TypeUri">
/// A URI reference that identifies the problem type. Consumers should use
/// <see cref="WellKnownProblemTypes"/> constants when possible.
/// </param>
/// <param name="Title">
/// A short, human-readable summary of the problem type. This should not
/// change between occurrences.
/// </param>
/// <param name="Status">
/// The HTTP status code generated by the origin server.
/// </param>
/// <param name="Detail">
/// A human-readable explanation specific to this occurrence of the problem.
/// </param>
/// <param name="Instance">
/// A URI reference that identifies the specific occurrence of the problem.
/// </param>
/// <param name="Extensions">
/// Additional members that extend the problem details — for example,
/// validation errors, trace IDs, or custom metadata.
/// </param>
public sealed record ProblemDetails(
    string? TypeUri = null,
    string? Title = null,
    int? Status = null,
    string? Detail = null,
    string? Instance = null,
    IReadOnlyDictionary<string, object?>? Extensions = null
);
